
$background = rgba(fdf7ffff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(f5eff7ff)

$inverse_primary = rgba(cfbdfeff)

$inverse_surface = rgba(322f35ff)

$on_background = rgba(1d1b20ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(201047ff)

$on_primary_fixed = rgba(201047ff)

$on_primary_fixed_variant = rgba(4c3e75ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(1e192bff)

$on_secondary_fixed = rgba(1e192bff)

$on_secondary_fixed_variant = rgba(4a4458ff)

$on_surface = rgba(1d1b20ff)

$on_surface_variant = rgba(49454eff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(31101dff)

$on_tertiary_fixed = rgba(31101dff)

$on_tertiary_fixed_variant = rgba(633b49ff)

$outline = rgba(7a757fff)

$outline_variant = rgba(cac4cfff)

$primary = rgba(64558fff)

$primary_container = rgba(e8ddffff)

$primary_fixed = rgba(e8ddffff)

$primary_fixed_dim = rgba(cfbdfeff)

$scrim = rgba(000000ff)

$secondary = rgba(625b71ff)

$secondary_container = rgba(e8def8ff)

$secondary_fixed = rgba(e8def8ff)

$secondary_fixed_dim = rgba(cbc2dcff)

$shadow = rgba(000000ff)

$source_color = rgba(6200eeff)

$surface = rgba(fdf7ffff)

$surface_bright = rgba(fdf7ffff)

$surface_container = rgba(f2ecf4ff)

$surface_container_high = rgba(ece6eeff)

$surface_container_highest = rgba(e6e1e9ff)

$surface_container_low = rgba(f8f2faff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(ded8e0ff)

$surface_tint = rgba(64558fff)

$surface_variant = rgba(e7e0ecff)

$tertiary = rgba(7d5260ff)

$tertiary_container = rgba(ffd9e3ff)

$tertiary_fixed = rgba(ffd9e3ff)

$tertiary_fixed_dim = rgba(efb8c8ff)

